const list = [{
    title: '佛跳墙',
    price: 88.88,
    number: 1,
    img: '佛跳墙.jpg'
}, {
    title: '翠堂菜拼金钱袋',
    price: 66.66,
    number: 1,
    img: '翠堂菜拼金钱袋.jpg'
}, {
    title: '果仁鸳鸯虾球',
    price: 55.55,
    number: 1,
    img: '果仁鸳鸯虾球.jpg'
}, {
    title: '海皇三鲜煎面',
    price: 11.11,
    number: 1,
    img: '海皇三鲜煎面.jpg'
}, {
    title: '黑醋法国鹅肝',
    price: 22.22,
    number: 1,
    img: '黑醋法国鹅肝.jpg'
}, {
    title: '家乡葱油饼',
    price: 33.33,
    number: 1,
    img: '家乡葱油饼.jpg'
}, {
    title: '金奖鳗鱼酥',
    price: 44.44,
    number: 1,
    img: '金奖鳗鱼酥.jpg'
}, {
    title: '上汤龙虾',
    price: 77.77,
    number: 1,
    img: '上汤龙虾.jpg'
}, {
    title: '深海金枪鱼',
    price: 99.99,
    number: 1,
    img: '深海金枪鱼.jpg'
}, {
    title: '野生水鱼焖鲍鱼鸡',
    price: 99.00,
    number: 1,
    img: '野生水鱼焖鲍鱼鸡.jpg'
}, {
    title: '佛跳墙',
    price: 88.88,
    number: 1,
    img: '佛跳墙.jpg'
}, {
    title: '翠堂菜拼金钱袋',
    price: 66.66,
    number: 1,
    img: '翠堂菜拼金钱袋.jpg'
}, {
    title: '果仁鸳鸯虾球',
    price: 55.55,
    number: 1,
    img: '果仁鸳鸯虾球.jpg'
}, {
    title: '海皇三鲜煎面',
    price: 11.11,
    number: 1,
    img: '海皇三鲜煎面.jpg'
}, {
    title: '黑醋法国鹅肝',
    price: 22.22,
    number: 1,
    img: '黑醋法国鹅肝.jpg'
}, {
    title: '家乡葱油饼',
    price: 33.33,
    number: 1,
    img: '家乡葱油饼.jpg'
}, {
    title: '金奖鳗鱼酥',
    price: 44.44,
    number: 1,
    img: '金奖鳗鱼酥.jpg'
}, {
    title: '上汤龙虾',
    price: 77.77,
    number: 1,
    img: '上汤龙虾.jpg'
}, {
    title: '深海金枪鱼',
    price: 99.99,
    number: 1,
    img: '深海金枪鱼.jpg'
}, {
    title: '野生水鱼焖鲍鱼鸡',
    price: 99.00,
    number: 1,
    img: '野生水鱼焖鲍鱼鸡.jpg'
}]